# Use root/example as user/password credentials
version: '3.3'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    restart: always
    env_file:
      - api.env
    ports:
        - 3306:3306


  adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - 8080:8080