# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # check docker-compose file
    - name: Check compose file
      run: docker-compose config

    # Build compose file
    - name: Build the stack
      run: docker-compose up -d
    
    #test adminer
    - name: Test Adminer
      run: docker run --network container:mysql-docker_adminer_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/

    - name: Test database
      run: |
        sleep 10 
        docker exec mysql-docker_db_1 mysqlcheck -uroot -pexample -A
      shell: bash

